//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.23 at 02:01:50 PM CEST 
//


package dk.diku.robust.autogen.knapsackexperiment;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeneticAlgorithmSetup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneticAlgorithmSetup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="population_size" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="use_scenario_seeding" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneticAlgorithmSetup")
public class GeneticAlgorithmSetup {

    @XmlAttribute(name = "population_size")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger populationSize;
    @XmlAttribute(name = "use_scenario_seeding")
    protected Boolean useScenarioSeeding;

    /**
     * Gets the value of the populationSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPopulationSize() {
        return populationSize;
    }

    /**
     * Sets the value of the populationSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPopulationSize(BigInteger value) {
        this.populationSize = value;
    }

    /**
     * Gets the value of the useScenarioSeeding property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseScenarioSeeding() {
        return useScenarioSeeding;
    }

    /**
     * Sets the value of the useScenarioSeeding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseScenarioSeeding(Boolean value) {
        this.useScenarioSeeding = value;
    }

}
