//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.23 at 02:01:50 PM CEST 
//


package dk.diku.robust.autogen.knapsackexperiment;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.diku.robust.autogen.knapsackexperiment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KnapsackExperiment_QNAME = new QName("http://www.diku.dk/robust/autogen/knapsackexperiment", "knapsack_experiment");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.diku.robust.autogen.knapsackexperiment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeneticAlgorithmSetup }
     * 
     */
    public GeneticAlgorithmSetup createGeneticAlgorithmSetup() {
        return new GeneticAlgorithmSetup();
    }

    /**
     * Create an instance of {@link ExperimentParameters }
     * 
     */
    public ExperimentParameters createExperimentParameters() {
        return new ExperimentParameters();
    }

    /**
     * Create an instance of {@link LocalSearchSetup }
     * 
     */
    public LocalSearchSetup createLocalSearchSetup() {
        return new LocalSearchSetup();
    }

    /**
     * Create an instance of {@link KnapsackExperiment }
     * 
     */
    public KnapsackExperiment createKnapsackExperiment() {
        return new KnapsackExperiment();
    }

    /**
     * Create an instance of {@link Simulation }
     * 
     */
    public Simulation createSimulation() {
        return new Simulation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KnapsackExperiment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.diku.dk/robust/autogen/knapsackexperiment", name = "knapsack_experiment")
    public JAXBElement<KnapsackExperiment> createKnapsackExperiment(KnapsackExperiment value) {
        return new JAXBElement<KnapsackExperiment>(_KnapsackExperiment_QNAME, KnapsackExperiment.class, null, value);
    }

}
