//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.31 at 11:37:18 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.diku.dk/robust/autogen/test", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dk.diku.robust.autogen.test;
