//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.22 at 02:00:41 PM CEST 
//


package dk.diku.robust.autogen.stochknapsack;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for distribution.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="distribution">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="discrete"/>
 *     &lt;enumeration value="normal"/>
 *     &lt;enumeration value="uniform"/>
 *     &lt;enumeration value="gamma"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "distribution")
@XmlEnum
public enum Distribution {

    @XmlEnumValue("discrete")
    DISCRETE("discrete"),
    @XmlEnumValue("normal")
    NORMAL("normal"),
    @XmlEnumValue("uniform")
    UNIFORM("uniform"),
    @XmlEnumValue("gamma")
    GAMMA("gamma");
    private final String value;

    Distribution(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Distribution fromValue(String v) {
        for (Distribution c: Distribution.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
