//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.22 at 02:00:41 PM CEST 
//


package dk.diku.robust.autogen.stochknapsack;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gammaDistribution complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gammaDistribution">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="shape" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="scale" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gammaDistribution")
public class GammaDistribution {

    @XmlAttribute(required = true)
    protected float shape;
    @XmlAttribute(required = true)
    protected float scale;

    /**
     * Gets the value of the shape property.
     * 
     */
    public float getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     */
    public void setShape(float value) {
        this.shape = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     */
    public float getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     */
    public void setScale(float value) {
        this.scale = value;
    }

}
