//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.22 at 02:00:41 PM CEST 
//


package dk.diku.robust.autogen.stochknapsack;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for itemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="itemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="profit" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *           &lt;element name="stochasticProfit" type="{http://www.diku.dk/robust/autogen/stochknapsack}distributionType"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *           &lt;element name="stochasticWeight" type="{http://www.diku.dk/robust/autogen/stochknapsack}distributionType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemType", propOrder = {
    "profit",
    "stochasticProfit",
    "weight",
    "stochasticWeight"
})
public class ItemType {

    protected Float profit;
    protected DistributionType stochasticProfit;
    protected Float weight;
    protected DistributionType stochasticWeight;

    /**
     * Gets the value of the profit property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getProfit() {
        return profit;
    }

    /**
     * Sets the value of the profit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setProfit(Float value) {
        this.profit = value;
    }

    /**
     * Gets the value of the stochasticProfit property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionType }
     *     
     */
    public DistributionType getStochasticProfit() {
        return stochasticProfit;
    }

    /**
     * Sets the value of the stochasticProfit property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionType }
     *     
     */
    public void setStochasticProfit(DistributionType value) {
        this.stochasticProfit = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWeight(Float value) {
        this.weight = value;
    }

    /**
     * Gets the value of the stochasticWeight property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionType }
     *     
     */
    public DistributionType getStochasticWeight() {
        return stochasticWeight;
    }

    /**
     * Sets the value of the stochasticWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionType }
     *     
     */
    public void setStochasticWeight(DistributionType value) {
        this.stochasticWeight = value;
    }

}
