//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.30 at 03:32:41 PM CET 
//


package dk.diku.robust.autogen.sclsp_scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CostAtTime complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CostAtTime">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unit_production_cost" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="fixed_production_cost" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="startup_cost" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="lead_time" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="unit_capacity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="setup_capacity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="time_period" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CostAtTime", propOrder = {
    "unitProductionCost",
    "fixedProductionCost",
    "startupCost",
    "leadTime",
    "unitCapacity",
    "setupCapacity"
})
public class CostAtTime {

    @XmlElement(name = "unit_production_cost")
    protected Integer unitProductionCost;
    @XmlElement(name = "fixed_production_cost")
    protected Integer fixedProductionCost;
    @XmlElement(name = "startup_cost")
    protected Integer startupCost;
    @XmlElement(name = "lead_time")
    protected Integer leadTime;
    @XmlElement(name = "unit_capacity")
    protected Integer unitCapacity;
    @XmlElement(name = "setup_capacity")
    protected Integer setupCapacity;
    @XmlAttribute(name = "time_period", required = true)
    protected int timePeriod;

    /**
     * Gets the value of the unitProductionCost property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUnitProductionCost() {
        return unitProductionCost;
    }

    /**
     * Sets the value of the unitProductionCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUnitProductionCost(Integer value) {
        this.unitProductionCost = value;
    }

    /**
     * Gets the value of the fixedProductionCost property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFixedProductionCost() {
        return fixedProductionCost;
    }

    /**
     * Sets the value of the fixedProductionCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFixedProductionCost(Integer value) {
        this.fixedProductionCost = value;
    }

    /**
     * Gets the value of the startupCost property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStartupCost() {
        return startupCost;
    }

    /**
     * Sets the value of the startupCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartupCost(Integer value) {
        this.startupCost = value;
    }

    /**
     * Gets the value of the leadTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLeadTime() {
        return leadTime;
    }

    /**
     * Sets the value of the leadTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLeadTime(Integer value) {
        this.leadTime = value;
    }

    /**
     * Gets the value of the unitCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUnitCapacity() {
        return unitCapacity;
    }

    /**
     * Sets the value of the unitCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUnitCapacity(Integer value) {
        this.unitCapacity = value;
    }

    /**
     * Gets the value of the setupCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSetupCapacity() {
        return setupCapacity;
    }

    /**
     * Sets the value of the setupCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSetupCapacity(Integer value) {
        this.setupCapacity = value;
    }

    /**
     * Gets the value of the timePeriod property.
     * 
     */
    public int getTimePeriod() {
        return timePeriod;
    }

    /**
     * Sets the value of the timePeriod property.
     * 
     */
    public void setTimePeriod(int value) {
        this.timePeriod = value;
    }

}
