//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.30 at 03:32:41 PM CET 
//


package dk.diku.robust.autogen.sclsp_scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GlobalParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GlobalParameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="time_periods" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="num_orders" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="num_items" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="num_resources" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlobalParameters")
public class GlobalParameters {

    @XmlAttribute(name = "time_periods", required = true)
    protected int timePeriods;
    @XmlAttribute(name = "num_orders", required = true)
    protected int numOrders;
    @XmlAttribute(name = "num_items", required = true)
    protected int numItems;
    @XmlAttribute(name = "num_resources", required = true)
    protected int numResources;

    /**
     * Gets the value of the timePeriods property.
     * 
     */
    public int getTimePeriods() {
        return timePeriods;
    }

    /**
     * Sets the value of the timePeriods property.
     * 
     */
    public void setTimePeriods(int value) {
        this.timePeriods = value;
    }

    /**
     * Gets the value of the numOrders property.
     * 
     */
    public int getNumOrders() {
        return numOrders;
    }

    /**
     * Sets the value of the numOrders property.
     * 
     */
    public void setNumOrders(int value) {
        this.numOrders = value;
    }

    /**
     * Gets the value of the numItems property.
     * 
     */
    public int getNumItems() {
        return numItems;
    }

    /**
     * Sets the value of the numItems property.
     * 
     */
    public void setNumItems(int value) {
        this.numItems = value;
    }

    /**
     * Gets the value of the numResources property.
     * 
     */
    public int getNumResources() {
        return numResources;
    }

    /**
     * Sets the value of the numResources property.
     * 
     */
    public void setNumResources(int value) {
        this.numResources = value;
    }

}
