//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.30 at 03:32:41 PM CET 
//


package dk.diku.robust.autogen.sclsp_scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Item">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="initial_inventory" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="production_costs" type="{http://www.diku.dk/robust/autogen/sclsp_scenario}ProductionCosts" minOccurs="0"/>
 *         &lt;element name="inventory_costs" type="{http://www.diku.dk/robust/autogen/sclsp_scenario}InventoryCosts" minOccurs="0"/>
 *         &lt;element name="bom_relations" type="{http://www.diku.dk/robust/autogen/sclsp_scenario}BOMRelations" minOccurs="0"/>
 *         &lt;element name="demands" type="{http://www.diku.dk/robust/autogen/sclsp_scenario}Demands" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Item", propOrder = {
    "initialInventory",
    "productionCosts",
    "inventoryCosts",
    "bomRelations",
    "demands"
})
public class Item {

    @XmlElement(name = "initial_inventory")
    protected int initialInventory;
    @XmlElement(name = "production_costs")
    protected ProductionCosts productionCosts;
    @XmlElement(name = "inventory_costs")
    protected InventoryCosts inventoryCosts;
    @XmlElement(name = "bom_relations")
    protected BOMRelations bomRelations;
    protected Demands demands;
    @XmlAttribute(required = true)
    protected int id;

    /**
     * Gets the value of the initialInventory property.
     * 
     */
    public int getInitialInventory() {
        return initialInventory;
    }

    /**
     * Sets the value of the initialInventory property.
     * 
     */
    public void setInitialInventory(int value) {
        this.initialInventory = value;
    }

    /**
     * Gets the value of the productionCosts property.
     * 
     * @return
     *     possible object is
     *     {@link ProductionCosts }
     *     
     */
    public ProductionCosts getProductionCosts() {
        return productionCosts;
    }

    /**
     * Sets the value of the productionCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductionCosts }
     *     
     */
    public void setProductionCosts(ProductionCosts value) {
        this.productionCosts = value;
    }

    /**
     * Gets the value of the inventoryCosts property.
     * 
     * @return
     *     possible object is
     *     {@link InventoryCosts }
     *     
     */
    public InventoryCosts getInventoryCosts() {
        return inventoryCosts;
    }

    /**
     * Sets the value of the inventoryCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventoryCosts }
     *     
     */
    public void setInventoryCosts(InventoryCosts value) {
        this.inventoryCosts = value;
    }

    /**
     * Gets the value of the bomRelations property.
     * 
     * @return
     *     possible object is
     *     {@link BOMRelations }
     *     
     */
    public BOMRelations getBomRelations() {
        return bomRelations;
    }

    /**
     * Sets the value of the bomRelations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BOMRelations }
     *     
     */
    public void setBomRelations(BOMRelations value) {
        this.bomRelations = value;
    }

    /**
     * Gets the value of the demands property.
     * 
     * @return
     *     possible object is
     *     {@link Demands }
     *     
     */
    public Demands getDemands() {
        return demands;
    }

    /**
     * Sets the value of the demands property.
     * 
     * @param value
     *     allowed object is
     *     {@link Demands }
     *     
     */
    public void setDemands(Demands value) {
        this.demands = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

}
