//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.30 at 03:32:41 PM CET 
//


package dk.diku.robust.autogen.sclsp_scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LotSizingScenario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LotSizingScenario">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text" type="{http://www.diku.dk/robust/autogen/sclsp_scenario}Text"/>
 *         &lt;element name="stop_criteria" type="{http://www.diku.dk/robust/autogen/sclsp_scenario}StopCriteria"/>
 *         &lt;element name="global_parameters" type="{http://www.diku.dk/robust/autogen/sclsp_scenario}GlobalParameters"/>
 *         &lt;element name="resources" type="{http://www.diku.dk/robust/autogen/sclsp_scenario}Resources"/>
 *         &lt;element name="items" type="{http://www.diku.dk/robust/autogen/sclsp_scenario}Items"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LotSizingScenario", propOrder = {
    "text",
    "stopCriteria",
    "globalParameters",
    "resources",
    "items"
})
public class LotSizingScenario {

    @XmlElement(required = true)
    protected Text text;
    @XmlElement(name = "stop_criteria", required = true)
    protected StopCriteria stopCriteria;
    @XmlElement(name = "global_parameters", required = true)
    protected GlobalParameters globalParameters;
    @XmlElement(required = true)
    protected Resources resources;
    @XmlElement(required = true)
    protected Items items;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setText(Text value) {
        this.text = value;
    }

    /**
     * Gets the value of the stopCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link StopCriteria }
     *     
     */
    public StopCriteria getStopCriteria() {
        return stopCriteria;
    }

    /**
     * Sets the value of the stopCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopCriteria }
     *     
     */
    public void setStopCriteria(StopCriteria value) {
        this.stopCriteria = value;
    }

    /**
     * Gets the value of the globalParameters property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalParameters }
     *     
     */
    public GlobalParameters getGlobalParameters() {
        return globalParameters;
    }

    /**
     * Sets the value of the globalParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalParameters }
     *     
     */
    public void setGlobalParameters(GlobalParameters value) {
        this.globalParameters = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link Resources }
     *     
     */
    public Resources getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resources }
     *     
     */
    public void setResources(Resources value) {
        this.resources = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link Items }
     *     
     */
    public Items getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link Items }
     *     
     */
    public void setItems(Items value) {
        this.items = value;
    }

}
