//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.30 at 03:32:41 PM CET 
//


package dk.diku.robust.autogen.sclsp_scenario;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.diku.robust.autogen.sclsp_scenario package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Instance_QNAME = new QName("http://www.diku.dk/robust/autogen/sclsp_scenario", "instance");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.diku.robust.autogen.sclsp_scenario
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GlobalParameters }
     * 
     */
    public GlobalParameters createGlobalParameters() {
        return new GlobalParameters();
    }

    /**
     * Create an instance of {@link ProductionCosts }
     * 
     */
    public ProductionCosts createProductionCosts() {
        return new ProductionCosts();
    }

    /**
     * Create an instance of {@link BOMRelations }
     * 
     */
    public BOMRelations createBOMRelations() {
        return new BOMRelations();
    }

    /**
     * Create an instance of {@link Capacities }
     * 
     */
    public Capacities createCapacities() {
        return new Capacities();
    }

    /**
     * Create an instance of {@link CostAtTime }
     * 
     */
    public CostAtTime createCostAtTime() {
        return new CostAtTime();
    }

    /**
     * Create an instance of {@link Resources }
     * 
     */
    public Resources createResources() {
        return new Resources();
    }

    /**
     * Create an instance of {@link Capacity }
     * 
     */
    public Capacity createCapacity() {
        return new Capacity();
    }

    /**
     * Create an instance of {@link LotSizingScenario }
     * 
     */
    public LotSizingScenario createLotSizingScenario() {
        return new LotSizingScenario();
    }

    /**
     * Create an instance of {@link Demands }
     * 
     */
    public Demands createDemands() {
        return new Demands();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link InventoryCosts }
     * 
     */
    public InventoryCosts createInventoryCosts() {
        return new InventoryCosts();
    }

    /**
     * Create an instance of {@link BOMRelation }
     * 
     */
    public BOMRelation createBOMRelation() {
        return new BOMRelation();
    }

    /**
     * Create an instance of {@link StopCriteria }
     * 
     */
    public StopCriteria createStopCriteria() {
        return new StopCriteria();
    }

    /**
     * Create an instance of {@link InventoryCost }
     * 
     */
    public InventoryCost createInventoryCost() {
        return new InventoryCost();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link CostOnResource }
     * 
     */
    public CostOnResource createCostOnResource() {
        return new CostOnResource();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Demand }
     * 
     */
    public Demand createDemand() {
        return new Demand();
    }

    /**
     * Create an instance of {@link Items }
     * 
     */
    public Items createItems() {
        return new Items();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LotSizingScenario }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.diku.dk/robust/autogen/sclsp_scenario", name = "instance")
    public JAXBElement<LotSizingScenario> createInstance(LotSizingScenario value) {
        return new JAXBElement<LotSizingScenario>(_Instance_QNAME, LotSizingScenario.class, null, value);
    }

}
