//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.30 at 03:32:41 PM CET 
//


package dk.diku.robust.autogen.sclsp_scenario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StopCriteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopCriteria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="branch_and_bound_nodes" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cpu_time_millis" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="optimality_gap" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopCriteria")
public class StopCriteria {

    @XmlAttribute(name = "branch_and_bound_nodes")
    protected Integer branchAndBoundNodes;
    @XmlAttribute(name = "cpu_time_millis")
    protected Integer cpuTimeMillis;
    @XmlAttribute(name = "optimality_gap")
    protected Float optimalityGap;

    /**
     * Gets the value of the branchAndBoundNodes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBranchAndBoundNodes() {
        return branchAndBoundNodes;
    }

    /**
     * Sets the value of the branchAndBoundNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBranchAndBoundNodes(Integer value) {
        this.branchAndBoundNodes = value;
    }

    /**
     * Gets the value of the cpuTimeMillis property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCpuTimeMillis() {
        return cpuTimeMillis;
    }

    /**
     * Sets the value of the cpuTimeMillis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCpuTimeMillis(Integer value) {
        this.cpuTimeMillis = value;
    }

    /**
     * Gets the value of the optimalityGap property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getOptimalityGap() {
        return optimalityGap;
    }

    /**
     * Sets the value of the optimalityGap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setOptimalityGap(Float value) {
        this.optimalityGap = value;
    }

}
