//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.28 at 05:22:47 PM CET 
//


package dk.diku.robust.autogen.sclsp_instance;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Item">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="time_period" type="{http://www.diku.dk/robust/autogen/sclsp_instance}TimePeriod" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="item_id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="initial_cost" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Item", propOrder = {
    "timePeriod"
})
public class Item {

    @XmlElement(name = "time_period", required = true)
    protected List<TimePeriod> timePeriod;
    @XmlAttribute(name = "item_id", required = true)
    protected int itemId;
    @XmlAttribute(name = "initial_cost", required = true)
    protected int initialCost;

    /**
     * Gets the value of the timePeriod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timePeriod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimePeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimePeriod }
     * 
     * 
     */
    public List<TimePeriod> getTimePeriod() {
        if (timePeriod == null) {
            timePeriod = new ArrayList<TimePeriod>();
        }
        return this.timePeriod;
    }

    /**
     * Gets the value of the itemId property.
     * 
     */
    public int getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     */
    public void setItemId(int value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the initialCost property.
     * 
     */
    public int getInitialCost() {
        return initialCost;
    }

    /**
     * Sets the value of the initialCost property.
     * 
     */
    public void setInitialCost(int value) {
        this.initialCost = value;
    }

}
