//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.28 at 05:22:47 PM CET 
//


package dk.diku.robust.autogen.sclsp_instance;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SCLSPInstance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SCLSPInstance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="item" type="{http://www.diku.dk/robust/autogen/sclsp_instance}Item" maxOccurs="unbounded"/>
 *         &lt;element name="capacity" type="{http://www.diku.dk/robust/autogen/sclsp_instance}Capacity" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="num_items" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="num_periods" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SCLSPInstance", propOrder = {
    "item",
    "capacity"
})
public class SCLSPInstance {

    @XmlElement(required = true)
    protected List<Item> item;
    @XmlElement(required = true)
    protected List<Capacity> capacity;
    @XmlAttribute(name = "num_items", required = true)
    protected int numItems;
    @XmlAttribute(name = "num_periods", required = true)
    protected int numPeriods;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Item }
     * 
     * 
     */
    public List<Item> getItem() {
        if (item == null) {
            item = new ArrayList<Item>();
        }
        return this.item;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capacity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapacity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Capacity }
     * 
     * 
     */
    public List<Capacity> getCapacity() {
        if (capacity == null) {
            capacity = new ArrayList<Capacity>();
        }
        return this.capacity;
    }

    /**
     * Gets the value of the numItems property.
     * 
     */
    public int getNumItems() {
        return numItems;
    }

    /**
     * Sets the value of the numItems property.
     * 
     */
    public void setNumItems(int value) {
        this.numItems = value;
    }

    /**
     * Gets the value of the numPeriods property.
     * 
     */
    public int getNumPeriods() {
        return numPeriods;
    }

    /**
     * Sets the value of the numPeriods property.
     * 
     */
    public void setNumPeriods(int value) {
        this.numPeriods = value;
    }

}
