//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.28 at 05:22:47 PM CET 
//


package dk.diku.robust.autogen.sclsp_instance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimePeriod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimePeriod">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="production_cost" type="{http://www.diku.dk/robust/autogen/sclsp_instance}Value" minOccurs="0"/>
 *         &lt;element name="holding_cost" type="{http://www.diku.dk/robust/autogen/sclsp_instance}Value" minOccurs="0"/>
 *         &lt;element name="fixed_cost" type="{http://www.diku.dk/robust/autogen/sclsp_instance}Value" minOccurs="0"/>
 *         &lt;element name="demand" type="{http://www.diku.dk/robust/autogen/sclsp_instance}Value" minOccurs="0"/>
 *         &lt;element name="cap_usage" type="{http://www.diku.dk/robust/autogen/sclsp_instance}Value" minOccurs="0"/>
 *         &lt;element name="cap_setup" type="{http://www.diku.dk/robust/autogen/sclsp_instance}Value" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="time_period" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimePeriod", propOrder = {
    "productionCost",
    "holdingCost",
    "fixedCost",
    "demand",
    "capUsage",
    "capSetup"
})
public class TimePeriod {

    @XmlElement(name = "production_cost")
    protected Value productionCost;
    @XmlElement(name = "holding_cost")
    protected Value holdingCost;
    @XmlElement(name = "fixed_cost")
    protected Value fixedCost;
    protected Value demand;
    @XmlElement(name = "cap_usage")
    protected Value capUsage;
    @XmlElement(name = "cap_setup")
    protected Value capSetup;
    @XmlAttribute(name = "time_period", required = true)
    protected int timePeriod;

    /**
     * Gets the value of the productionCost property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getProductionCost() {
        return productionCost;
    }

    /**
     * Sets the value of the productionCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setProductionCost(Value value) {
        this.productionCost = value;
    }

    /**
     * Gets the value of the holdingCost property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getHoldingCost() {
        return holdingCost;
    }

    /**
     * Sets the value of the holdingCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setHoldingCost(Value value) {
        this.holdingCost = value;
    }

    /**
     * Gets the value of the fixedCost property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getFixedCost() {
        return fixedCost;
    }

    /**
     * Sets the value of the fixedCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setFixedCost(Value value) {
        this.fixedCost = value;
    }

    /**
     * Gets the value of the demand property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getDemand() {
        return demand;
    }

    /**
     * Sets the value of the demand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setDemand(Value value) {
        this.demand = value;
    }

    /**
     * Gets the value of the capUsage property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getCapUsage() {
        return capUsage;
    }

    /**
     * Sets the value of the capUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setCapUsage(Value value) {
        this.capUsage = value;
    }

    /**
     * Gets the value of the capSetup property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getCapSetup() {
        return capSetup;
    }

    /**
     * Sets the value of the capSetup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setCapSetup(Value value) {
        this.capSetup = value;
    }

    /**
     * Gets the value of the timePeriod property.
     * 
     */
    public int getTimePeriod() {
        return timePeriod;
    }

    /**
     * Sets the value of the timePeriod property.
     * 
     */
    public void setTimePeriod(int value) {
        this.timePeriod = value;
    }

}
