//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.06 at 10:10:37 AM CET 
//


package dk.diku.robust.autogen.sclsp_solution;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.diku.robust.autogen.sclsp_solution package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Solution_QNAME = new QName("http://www.diku.dk/robust/autogen/sclsp_solution", "solution");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.diku.robust.autogen.sclsp_solution
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResourceBeingSetup }
     * 
     */
    public ResourceBeingSetup createResourceBeingSetup() {
        return new ResourceBeingSetup();
    }

    /**
     * Create an instance of {@link BeingSetupTimePeriod }
     * 
     */
    public BeingSetupTimePeriod createBeingSetupTimePeriod() {
        return new BeingSetupTimePeriod();
    }

    /**
     * Create an instance of {@link IsSetupTimePeriods }
     * 
     */
    public IsSetupTimePeriods createIsSetupTimePeriods() {
        return new IsSetupTimePeriods();
    }

    /**
     * Create an instance of {@link ItemOnStock }
     * 
     */
    public ItemOnStock createItemOnStock() {
        return new ItemOnStock();
    }

    /**
     * Create an instance of {@link GlobalParameters }
     * 
     */
    public GlobalParameters createGlobalParameters() {
        return new GlobalParameters();
    }

    /**
     * Create an instance of {@link StockTimePeriods }
     * 
     */
    public StockTimePeriods createStockTimePeriods() {
        return new StockTimePeriods();
    }

    /**
     * Create an instance of {@link StockTimePeriod }
     * 
     */
    public StockTimePeriod createStockTimePeriod() {
        return new StockTimePeriod();
    }

    /**
     * Create an instance of {@link ResourceIsSetup }
     * 
     */
    public ResourceIsSetup createResourceIsSetup() {
        return new ResourceIsSetup();
    }

    /**
     * Create an instance of {@link IsSetupTimePeriod }
     * 
     */
    public IsSetupTimePeriod createIsSetupTimePeriod() {
        return new IsSetupTimePeriod();
    }

    /**
     * Create an instance of {@link CLSPSolution }
     * 
     */
    public CLSPSolution createCLSPSolution() {
        return new CLSPSolution();
    }

    /**
     * Create an instance of {@link BeingSetupTimePeriods }
     * 
     */
    public BeingSetupTimePeriods createBeingSetupTimePeriods() {
        return new BeingSetupTimePeriods();
    }

    /**
     * Create an instance of {@link ProductionTimePeriods }
     * 
     */
    public ProductionTimePeriods createProductionTimePeriods() {
        return new ProductionTimePeriods();
    }

    /**
     * Create an instance of {@link ProductionTimePeriod }
     * 
     */
    public ProductionTimePeriod createProductionTimePeriod() {
        return new ProductionTimePeriod();
    }

    /**
     * Create an instance of {@link ItemProduction }
     * 
     */
    public ItemProduction createItemProduction() {
        return new ItemProduction();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CLSPSolution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.diku.dk/robust/autogen/sclsp_solution", name = "solution")
    public JAXBElement<CLSPSolution> createSolution(CLSPSolution value) {
        return new JAXBElement<CLSPSolution>(_Solution_QNAME, CLSPSolution.class, null, value);
    }

}
